home/urls.py
from django.contrib import admin
from django.urls import path,include
from home import views
from .views import *
from django.contrib.auth.views import LoginView,LogoutView

app_name = 'home'

urlpatterns =[
    path('/', views.index, name="base"),

    path('', views.IndexView.as_view(), name="home"),

    path('aboutus/', views.aboutus, name="aboutus"),

    path('contactus/', views.contactus, name="contactus"),

    path('allproduct', AllProductView.as_view(), name="allproduct"),

    # path('category/<str:pk>', views.CategoryView.as_view(), name='category'),

    path('create', views.ProductCreateView.as_view(), name='products-create'),

    path('product/<str:pk>',views.productDetails, name='productDetails'),

    path('create', views.CustomerCreateView.as_view(), name='customers-create'),

    path('create',views.OrderCreateView.as_view(), name='orders-create'),

    # path('register/', CustomerRegistrationView.as_view(),name="customerregistration"),

    # path("logout/",CustomerLogoutView.as_view(),name="customerlogout"),

    # path("customerlogin/",CustomerLoginView.as_view(),name="customerlogin"),

    path("profile/",CustomerProfileView.as_view(),name="customerprofile"),
    path("profile/order-<int:pk>/", CustomerOrderDetailView.as_view(),
         name="customerorderdetail"),



    path("myorder/",MyOrderDetailView.as_view(),name="myorder"),

    #cart
    # path("add-to-cart-<int:product_id>/",views.cart_add, name="addtocart"),
    path("add-to-cart-<int:pro_id>/", AddToCartView.as_view(), name="add-to-cart"),
    path("my-cart/", MyCartView.as_view(), name="mycart"),
    path("manage-cart/<int:cp_id>/", ManageCartView.as_view(), name="managecart"),
    path("empty-cart/", EmptyCartView.as_view(), name="emptycart"),

    path("checkout/", CheckoutView.as_view(), name="checkout"),

    

#    path('accounts/', include('accounts.urls', namespace='accounts')),


    #category--collection
    path('collections',views.collections,name="collections"),
    path('collections/<str:slug>',views.collectionsviews, name='collectionsview'),


    #payments   
    path("khalti-request/", KhaltiRequestView.as_view(), name="khaltirequest"),
    path("khalti-verify/", KhaltiVerifyView.as_view(), name="khaltiverify"),
    path("esewa-request/", EsewaRequestView.as_view(), name="esewarequest"),
    path("esewa-verify/", EsewaVerifyView.as_view(), name="esewaverify"),
   

]

lvdsuppliers/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('home/',include('home.urls')),
    path('accounts/',include('accounts.urls')),
    
]
urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dashboard/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import RegexValidator

# Create your models here.

class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=50)

    def __str__(self):
        return self.user.username


#category models
class Category(models.Model):
    title = models.CharField(max_length=255,unique=True)
    slug = models.SlugField()
    image = models.ImageField(upload_to= 'categories/',null=True)
    status = models.BooleanField(default=False, help_text="0_default, 1=Hidden")

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"
        ordering = ('id',)

    def __str__(self):
        return self.title 
    

#Brand Models
class Brand(models.Model):
    brand_code = models.CharField(max_length=200,null=True)
    name = models.CharField(max_length=200)
    slug =models.SlugField()

    class Meta:
        verbose_name ="Brand"
        verbose_name_plural = "brands"
        ordering= ('id',)

    def __str__(self):
        return self.name


class SizeVariant(models.Model):
    size_name = models.CharField(max_length=255)

    def  __str__(self) -> str:
        return self.size_name


#Product models
class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products' ,null=True)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE,related_name='products',blank=True,null=True)
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to = 'products/')
    # size_variant = models.ManyToManyField(SizeVariant, blank=True)
    price = models.PositiveIntegerField()
    slug = models.SlugField()
    description = models.CharField(max_length=300)
    is_latest = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'products'
        ordering = ('id',)
    
    def __str__(self):
        return self.name
    
    
    
class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products/")

    def __str__(self):
        return self.product.title
    
# class ProductSize(models.Model):
#     Size = models.ForeignKey(Size, on_delete=models.CASCADE)
#     product = models.ForeignKey(Product, on_delete=models.CASCADE)
#     count = models.IntegerField(default=1)
    
    
#Customer models
class Customer(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    # username = models.CharField(null=True,max_length=200)
    email_regex = RegexValidator(regex=  r"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$", message="please provide valid email address")
    email = models.EmailField(validators=[email_regex],unique=True)
    fn_regex = RegexValidator(regex=r"^[A-Za-z\s]+$", message="please provide valid Name")
    full_name = models.CharField(validators=[fn_regex],max_length=200, null=True)
    # profile_pic= models.ImageField(upload_to='profile_pic/CustomerProfilePic/',null=True,blank=True)
    address = models.CharField(max_length=40)
    contact_regex = RegexValidator( regex = r"^98\d{8}$",message = "phone number should starts with 98 and have 10 digits")
    contact = models.CharField(max_length=10,validators=[contact_regex],null=True)
    created_date = models.DateTimeField(auto_now_add=True,null=True)
    
    
    def __str__(self):
        return self.full_name
    



#Cart Models
class Cart(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL,null=True,blank=True)
    total = models.PositiveIntegerField(default=0)
    # is_paid = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    # def get_cart_total(self):
    #     cart_products = self.cart_products.all()
    #     price = []
    #     for cart_product in cart_product:
    #         price.append(cart_product.product.price)
    #         if cart_product.sizes:
    #             sizes_price = cart_product.sizes.price
    #             price.append(sizes_price)

    #     return sum(price)
    def __str__(self):
        return "Cart: " + str(self.id)
    

class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete = models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    size_variant = models.ForeignKey(SizeVariant,on_delete=models.SET_NULL, null=True,blank=True)
    subtotal = models.PositiveIntegerField()

    def __str__(self):
        return "Cart: " + str(self.cart.id) + " CartProduct: " + str(self.id)

    # def get_product_price(self):
    #     price = [self.product.price]

    #     if self.sizes:
    #         sizes_price =self.sizes.price
    #         price.append(sizes_price)
        
    #     return sum(price)
        

ORDER_STATUS = (
    ("Order Received", "Order Received"),
    ("Order Processing", "Order Processing"),
    ("On the way", "On the way"),
    ("Order Completed", "Order Completed"),
    ("Order Canceled", "Order Canceled"),
)

METHOD = (
    ("Cash On Delivery", "Cash On Delivery"),
    # ("Khalti", "Khalti"),
    ("Esewa", "Esewa"),
)


class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ob_regex = RegexValidator(regex=r"^[A-Za-z\s]+$", message="please provide valid Name")
    ordered_by = models.CharField(validators=[ob_regex],max_length=200)
    shipping_address = models.CharField(max_length=200)
    mobile_regex = RegexValidator( regex = r"^98\d{8}$",message = "phone number should exactly be in 10 digits and starts with 98")
    mobile = models.CharField(max_length=10, validators=[mobile_regex])
    email_regex = RegexValidator(regex=  r"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$", message="please provide valid email address")
    email = models.EmailField(validators=[email_regex],null=True, blank=True)
    subtotal = models.PositiveIntegerField()
    # discount = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=50, choices=ORDER_STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    payment_method = models.CharField(
        max_length=20, choices=METHOD, default="Cash On Delivery")
    payment_completed = models.BooleanField(
        default=False, null=True, blank=True)

    def __str__(self):
        return "Order: " + str(self.id)
    

# class Sale(models.Model):
#     date = models.DateTimeField()
#     amount = models.DecimalField(max_digits=10,decimal_places=2)

#     def __str__(self):
#         return f"Sale on {self.date} - ${self.amount}"

home/models.py
from django.db import models

# Create your models here.

home/forms.py
from django import forms
from django.contrib.auth import get_user_model
from . import models
from dashboard.models import Customer,Order
from django.contrib.auth.models import User

class CheckoutForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ["ordered_by", "shipping_address",
                  "mobile", "email", "payment_method"]
        

    

home/templates/home/carts/addtocart.html
{% extends 'home/base.html' %}

{% block title %} Add To Cart{% endblock %}

{% block main %}



    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                {% comment %} <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li> {% endcomment %}

                <script>
                    alertify.success("{{ message}}");
                </script>

            {% endfor %}
        </ul>
    {% endif %}



{% endblock %}

home/templates/home/carts/mycart.html
{% extends 'home/base.html' %}

{% block title %} My Cart{% endblock%}

{% block main%}

<section class="h-100 gradient-custom py-2" style="margin-top:105px;">
  <div class="container py-5">
    <div class="row d-flex justify-content-center my-4">
      <div class="col-md-8">
        <div class="card mb-4">
          <div class="card-header py-3">
            <h5 class="mb-0">Cart</h5>
          </div>
          <div class="card-body">
            {% for cp in cart.cartproduct_set.all %}
            <!-- Single item -->
            <div class="row">
              
              <div class="col-lg-3 col-md-12 mb-4 mb-lg-0">
                <!-- Image -->
                <div class="bg-image hover-overlay hover-zoom ripple rounded" data-mdb-ripple-color="light">
                  <img src="{{cp.product.image.url}}"
                    class="w-100" alt="Blue Jeans Jacket" />
                  <a href="#!">
                    <div class="mask" style="background-color: rgba(251, 251, 251, 0.2)"></div>
                  </a>
                </div>
                <!-- Image -->
              </div>

              <div class="col-lg-5 col-md-6 mb-4 mb-lg-0">
                <!-- Data -->
                <p><strong>{{cp.product.name}}</strong></p>
                <p>Price: {{cp.rate}}</p>
                <a href="{% url 'home:managecart' cp.id %}?action=rmv"><button type="button" class="btn btn-primary btn-sm me-1 mb-2" data-mdb-toggle="tooltip"
                  title="Remove item">
                  <i class="fas fa-trash"></i>
              </button></a>
                <!-- Data -->
              </div>

              <div class="col-lg-4 col-md-6 mb-4 mb-lg-0">
                <!-- Quantity -->
                <div class="d-flex mb-4" style="max-width: 300px">
                  <a href="{% url 'home:managecart' cp.id %}?action=dcr"><button class="btn btn-primary px-3 me-2">
                    <i class="fas fa-minus"></i>
                  </button></a>

                  <div class="form-outline">
                    <span class="quantity text-center">{{cp.quantity}}</span>
                  </div>

                  <a href="{% url 'home:managecart' cp.id %}?action=inc"><button class="btn btn-primary px-3 ms-2">
                    <i class="fas fa-plus"></i>
                  </button></a>
                </div>
                <!-- Quantity -->

                <!-- Price -->
                <p class="text-start text-xl-center text-success">
                  <strong>Subtotal: {{cp.subtotal}}</strong>
                </p>
                <!-- Price -->
              </div>
            </div>
            <!-- Single item -->

            <hr class="my-4" />
            
            {%endfor%}
            <div class="p-2">
              <h6 class="mb-0"><a href="{% url 'home:allproduct' %}" class="text-body"><i
                    class="fas fa-long-arrow-alt-left me-2"></i>Back to shop</a></h6>
                    {% if cart.cartproduct_set.all %}
                    <a href="{% url 'home:emptycart' %}">
                    <button type="button" class="float-end btn btn-primary btn-lg btn-block">
                      Empty Cart
                    </button></a>
                    {% endif %}
            </div>
           
              
            
          </div>
        </div>
      </div>


      <div class="col-md-4">
        <div class="card mb-4">
          <div class="card-header py-3">
            <h5 class="mb-0">Summary</h5>
          </div>
          <div class="card-body">
            
            <ul class="list-group list-group-flush">
              
              <li
                class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
                <div>
                  <strong>Total amount</strong>
                </div>
                <span><strong>Rs {{cart.total}}</strong></span>
              </li>
            </ul>
            {% if cart.cartproduct_set.all %}
              <a href="{% url 'home:checkout' %}">
            <button type="button" class="btn btn-primary btn-lg btn-block">
              Go to checkout
            </button></a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
</section>




{% endblock %}