accounts/urls.py
from django.urls import path,include
from . import views 
from .views import *
from django.contrib.auth.views import LoginView, LogoutView





app_name = 'accounts'

urlpatterns = [
   # path('adminclick', views.adminLoginView),
   # path('adminlogin', LoginView.as_view(template_name='account/adminlogin.html'),name='adminlogin'),
   # path('afterlogin', views.afterlogin_view,name='afterlogin'),
   # path('logout', LogoutView.as_view(template_name='ecom/logout.html'),name='logout'),
   # path('logout', views.customerSignUpView(), name = 'logout')


   path("register/",
         CustomerRegistrationView.as_view(), name="customerregistration"),

    path("logout/", CustomerLogoutView.as_view(), name="customerlogout"),
    path("login/", CustomerLoginView.as_view(), name="customerlogin"), 


   # path('login',views.AdminLoginViews.as_view(),name='login'),
   path('adminlogout',views.AdminLogoutViews.as_view(),name='adminlogout'),


   # path("registerform/",views.registerform, name="registerform"),
   # path("loginform/",views.loginform, name="loginform"),
   path("adminloginform/",AdminLoginViews.as_view(), name="adminloginform"),
   # path('logout/', views.logoutuser),



]

home/urls.py
from django.contrib import admin
from django.urls import path,include
from home import views
from .views import *
from django.contrib.auth.views import LoginView,LogoutView

app_name = 'home'

urlpatterns =[
    path('/', views.index, name="base"),

    path('', views.IndexView.as_view(), name="home"),

    path('aboutus/', views.aboutus, name="aboutus"),

    path('contactus/', views.contactus, name="contactus"),

    path('allproduct', AllProductView.as_view(), name="allproduct"),

    # path('category/<str:pk>', views.CategoryView.as_view(), name='category'),

    path('create', views.ProductCreateView.as_view(), name='products-create'),

    path('product/<str:pk>',views.productDetails, name='productDetails'),

    path('create', views.CustomerCreateView.as_view(), name='customers-create'),

    path('create',views.OrderCreateView.as_view(), name='orders-create'),

    # path('register/', CustomerRegistrationView.as_view(),name="customerregistration"),

    # path("logout/",CustomerLogoutView.as_view(),name="customerlogout"),

    # path("customerlogin/",CustomerLoginView.as_view(),name="customerlogin"),

    path("profile/",CustomerProfileView.as_view(),name="customerprofile"),
    path("profile/order-<int:pk>/", CustomerOrderDetailView.as_view(),
         name="customerorderdetail"),



    path("myorder/",MyOrderDetailView.as_view(),name="myorder"),

    #cart
    # path("add-to-cart-<int:product_id>/",views.cart_add, name="addtocart"),
    path("add-to-cart-<int:pro_id>/", AddToCartView.as_view(), name="add-to-cart"),
    path("my-cart/", MyCartView.as_view(), name="mycart"),
    path("manage-cart/<int:cp_id>/", ManageCartView.as_view(), name="managecart"),
    path("empty-cart/", EmptyCartView.as_view(), name="emptycart"),

    path("checkout/", CheckoutView.as_view(), name="checkout"),

    

#    path('accounts/', include('accounts.urls', namespace='accounts')),


    #category--collection
    path('collections',views.collections,name="collections"),
    path('collections/<str:slug>',views.collectionsviews, name='collectionsview'),


    #payments   
    path("khalti-request/", KhaltiRequestView.as_view(), name="khaltirequest"),
    path("khalti-verify/", KhaltiVerifyView.as_view(), name="khaltiverify"),
    path("esewa-request/", EsewaRequestView.as_view(), name="esewarequest"),
    path("esewa-verify/", EsewaVerifyView.as_view(), name="esewaverify"),
   

]

lvdsuppliers/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('home/',include('home.urls')),
    path('accounts/',include('accounts.urls')),
    
]
urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager

from django.contrib.auth.models import PermissionsMixin
# from django.utils.translation import ugettext_lazy as _
# from accounts.managers import CustomUserManager

# # Create your models here.
# class User(AbstractUser):
#     class Role(models.TextChoices):
#         ADMIN = 'admin', 'Admin'
#         CUSTOMER = "CUSTOMER", "Customer"

#     role = models.CharField(max_length=50,choices=Role.choices,default=Role.ADMIN)

# class CustomerManager(BaseUserManager):
#     def create_user(self, email, password=None, **extra_fields):
#         extra_fields.setdefault("role",User.Role.CUSTOMER)
#         extra_fields.setdefault("is_staff", False)
#         extra_fields.setdefault("is_superuser", False)

#         if not email:
#             raise ValueError("The Email field must be set")

#         email = self.normalize_email(email)
#         user = self.model(email=email, **extra_fields)
#         user.set_password(password)
#         user.save(using=self._db)
#         return user

#     def get_queryset(self, *args, **kwargs):
#         results = super().get_queryset(*args, **kwargs)
#         return results.filter(role=User.Role.CUSTOMER)
    
# class Customer(User):
#     base_role = User.Role.CUSTOMER
#     objects = CustomerManager()

#     class Meta:
#         proxy = True

#     def welcome(self):
#         return "only for customers"


# class CustomerProfile(models.Model):
#     user = models.OneToOneField(
#         User, on_delete=models.CASCADE, related_name="customer_profile", null=True
#     )
#     cus_email = models.CharField(max_length=50, blank=True, null=True)
#     cus_pwd = models.CharField(max_length=255, blank=True, null=True)
#     cus_name = models.CharField(max_length=50, blank=True, null=True)
#     cus_contact = models.PositiveBigIntegerField(blank=True, null=True)
#     cus_address = models.CharField(max_length=100)
#     reg_date = models.DateField(null=True, blank=True)
#     is_active = models.BooleanField(default=True)
#     admin_id = models.ForeignKey(
#         User,
#         on_delete=models.CASCADE,
#         related_name="admin_customer_profiles",
#         blank=False,
#     )

#     class Meta:
#         verbose_name = "Customer"
#         verbose_name_plural = "Customers"
#         ordering = ("id",)

#     def __str__(self):
#         return self.cus_name

# class CustomUser(AbstractUser):
#     username = None
#     email = models.EmailField(('email address'), unique=True)
#     USERNAME_FIELD = 'email'
#     REQUIRED_FIELD = []

#     objects = CustomUserManager()

#     def __str__(self):
#         return self.email

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from . import models
# from accounts.models import CustomUser
from dashboard.models import Customer
# from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django.core import validators

# def starts_with_address(value):
#     if value != '\d+\s+([A-Za-z]+\s?)+,\s*\w+,\s*\w+\s*\d*$':
#         raise forms.ValidationError('Address must contain 5 letters')
    

# def starts_with_98(value):
#     if value != '98':
#         raise forms.ValidationError('Number must start with 98')


class CustomerRegistrationForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())
    email = forms.CharField(widget=forms.EmailInput())
    # full_name = forms.CharField(widget=forms.TextInput())
    # address = forms.CharField(validators=[starts_with_address])
    # contact = forms.IntegerField(validators=[starts_with_98])

    class Meta:
        model = Customer
        fields = ["username", "password", "email", "full_name", "address","contact"]

    def clean_username(self):
        uname = self.cleaned_data.get("username")
        if User.objects.filter(username=uname).exists():
            raise forms.ValidationError(
                "Customer with this username already exists.")

        return uname
    
class CustomerLoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())



class AdminLoginForm(forms.Form):
    email = forms.CharField()
    password = forms.CharField(widget = forms.PasswordInput)

    class Meta:
        fields = ['email','password']

    def clean(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')

        error = forms.ValidationError({
            'email' : 'Email or Password didn\'t match.'
        })

        user_queryset = User.objects.filter(email=email)
        if not user_queryset.exists():
            raise error
        
        user = user_queryset.first()
        if not user.check_password(password):
            raise error
        
        self.instance = user

# class AdminLoginForm(UserCreationForm):
#     username= forms.CharField()
#     password= forms.CharField(widget=forms.PasswordInput)




# class CustomUserCreationForm(UserCreationForm):

#     class Meta(UserCreationForm):
#         model = CustomUser
#         fields = ('email',)


# class CustomUserChangeForm(UserChangeForm):

#     class Meta:
#         model = CustomUser
#         fields = ('email',)

accounts/views.py
from django.shortcuts import render,redirect
from django.views import View
from django.views.generic import CreateView, FormView
from .models import *
from django.urls import reverse_lazy
from django.views.generic import FormView
from django.contrib.auth import login,logout,authenticate
from .forms import AdminLoginForm, User,CustomerLoginForm,CustomerRegistrationForm
from dashboard.models import Admin, Customer
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
import re


 
# Create your views here.

# class AdminLoginViews(FormView):
#     template_name = 'accounts/login.html'
#     form_class = AdminLoginForm
    

#     def form_valid(self, form):
#         login(self.request, form.instance)
#         return redirect(reverse_lazy('dashboard:home'))
    

# def AdminLoginViews(request):
#     msg = None
#     if request.method == 'POST':
#         username = request.POST['username']
#         password = request.POST['password']
#         user = authenticate(request, username=username, password=password)

#         if user is not None and user.is_staff:
#             login(request, user)
#             # Redirect to admin dashboard or wherever you want
#             msg = "admin logged in successfully"
#             return redirect('dashboard:home')
#         else:
#             # Display an error message
#             msg = "Invalid credential"
#             error_message = "Invalid credentials. Please try again."
#             return render(request, 'accounts/login.html', {'error_message': error_message})
#     else:
#         return render(request, 'accounts/login.html')
class AdminLoginViews(FormView):
    template_name = "accounts/login.html"
    form_class = CustomerLoginForm
    success_url = reverse_lazy("dashboard:home")

    def form_valid(self, form):
        uname = form.cleaned_data.get("username")
        pword = form.cleaned_data["password"]
        usr = authenticate(username=uname, password=pword)
        if usr is not None and Admin.objects.filter(user=usr).exists():
            login(self.request, usr)
        else:
            return render(self.request, self.template_name, {"form": self.form_class, "error": "Invalid credentials"})
        return super().form_valid(form)



class AdminLogoutViews(FormView):
    def get(self, request, *args, **kwargs):
        logout(self.request)
        return redirect(reverse_lazy('accounts:adminloginform'))


class CustomerRegistrationView(CreateView):
    template_name = "accounts/customerregistration.html"
    form_class = CustomerRegistrationForm
    success_url = reverse_lazy('home:home')

    def form_valid(self,form):
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        email = form.cleaned_data.get("email")
        user = User.objects.create_user(username, email, password)
        form.instance.user = user
        login(self.request, user)
        return super().form_valid(form)

    def get_success_url(self):
        if "next" in self.request.GET:
            next_url = self.request.GET.get("next")
            return next_url
        else:
            return self.success_url




class CustomerLogoutView(View):
    def get(self, request):
        logout(request)
        return redirect("home:home")


class CustomerLoginView(FormView):
    template_name = "accounts/customerlogin.html"
    form_class = CustomerLoginForm
    success_url = reverse_lazy("home:home")

    # form_valid method is a type of post method and is available in createview formview and updateview
    def form_valid(self, form):
        uname = form.cleaned_data.get("username")
        pword = form.cleaned_data["password"]
        usr = authenticate(username=uname, password=pword)
        if usr is not None and Customer.objects.filter(user=usr).exists():
            login(self.request, usr)
        else:
            return render(self.request, self.template_name, {"form": self.form_class, "error": "Invalid credentials"})

        return super().form_valid(form)

    def get_success_url(self):
        if "next" in self.request.GET:
            next_url = self.request.GET.get("next")
            return next_url
        else:
            return self.success_url


# def logoutuser(request):
#     logout(request)
#     return redirect('/accounts/login')

accounts/templates/accounts/customerlogin.html
{% extends 'home/base.html' %}

{% block title %}Customer Login{% endblock %}

{% block form %}
<style>
    .errorlist {
        color: red;
    }
</style>
<div class="container-form">
    <input type="checkbox" id="check">
    <div class="login form">
      <header>Login Form</header>
      <form action="" method="POST">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Enter your username">
        <input type="password" name="password" placeholder="Enter your password">
       <button class="button">Login</button>
       {% if error %}

       <li style="color:red;">{{error}}</li>
 
       {% endif %}
    </form>
    <span class="signup">Don't have an account?
        <label for="check"><a href="{% url 'accounts:customerregistration' %}">Register here</a></label>
       </span>
    
     
    </div>
 
  </div>
{% endblock %}

accounts/templates/accounts/customerregistration.html
{% extends 'home/base.html' %}

{% block title %} Customer Registration{%endblock%}

{% block form %}
<style>
    .errorlist{
        color: red;
    }
    {% comment %} .form-container{
        background-color:white;
        border-radius:20px;
        box-sizing:border-box;
        height:500px;
        width:320px;
        align-items:center;
    }
    .form-welcome{
        color:#eee;
        font-family:sans-serif;
        font-size:36px;
        font-weight:600px;
        margin-top:30px;
    } {% endcomment %}

</style>

{% comment %}
<div class="form-container">
    <div class="form-welcome">
        
   
    
            <form action="" method="POST" class="main-form">
                {% csrf_token %}
                <div class="line-design">{{form.as_p}}</div>
                <button class="btn btn-primary">Register as a customer</button>
            </form>
        </div>
    
</div>
{% endcomment %}
<div class="container-regform">
    <input type="checkbox" id="check">
    <div class="registration form">
		{% comment %} {% for message in messages %}
			{% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
			<h6 id="messages" class="success_message py-3 px-1 my-2 text-center">{{message}}</h6>
			{% endif %}

			{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR%}
			<h6 id="messages" class="error_message py-3 px-1 my-2 text-center">{{message}}{{form.errors}}</h6>

			{% endif %}
		{% endfor %} {% endcomment %}
        <header>Signup Form</header>
    <form action="" method="POST">
        {% csrf_token %}
        
         {{form.as_p}} 

            {% comment %} <input type="text" class="form-control" value="{{ username }}" name="username" placeholder="Username">
            {% if errors.username %}
            <p class="error">{{ errors.username }}</p>
            {% endif %}

            <input type="password" class="form-control" value="{{ Password }}" name="Password" placeholder="Password">
            {% if errors.Password %}
            <p class="error">{{ errors.Password }}</p>
            {% endif %}
       
            <input type="email" class="form-control" value="{{ email }}" name="email" placeholder="Email">
            {% if errors.email %}
            <p class="error">{{ errors.email }}</p>
            {% endif %}

            <input type="text" class="form-control" value="{{ address }}" name="address" placeholder="Address">
            {% if errors.address %}
            <p class="error">{{ errors.address }}</p>
            {% endif %} 

            <input type="text" class="form-control" value="{{ contact }}" name="contact" placeholder="Contact">
            {% if errors.contact %}
            <p class="error">{{ errors.contact }}</p>
            {% endif %} {% endcomment %}
         
            
            
            {% comment %} {% for message in messages %}
			{% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
			<h6 id="messages" class="success_message py-3 px-1 my-2 text-center">{{message}}</h6>
			{% endif %}

			{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR%}
			<h6 id="messages" class="error_message py-3 px-1 my-2 text-center">{{message}}{{form.errors}}</h6>

			{% endif %}
			{% endfor %} {% endcomment %}
        {% comment %} {{form.as_p}} {% endcomment %}
            {% comment %} <input type="text" name="username" placeholder="Enter your username">
            <input type="password" name="password" placeholder="Enter your password"> 
            <input type="email" name="email" placeholder="Enter your email">
            <input type="text" name="full_name" placeholder="Enter your full name">
            <input type="text" name="address" placeholder="Enter your address">
            <input type="number" name="contact" placeholder="Enter your contact no."> {% endcomment %}



        <button class="button">Register</button>
        {% if error %}

        <li style="color:red;">{{errors}}</li>
  
        {% endif %}
    </form>
    
    <div class="signup">
      <span class="signup">Already have an account?
       <label for="check"><a href="{% url 'accounts:customerlogin' %}">Login</a></label>
      </span>
    </div>
  </div>
</div>


{%endblock%}

accounts/templates/accounts/login.html
{% comment %} {% extends 'home/base.html' %}

{% block title %}Customer Login{% endblock %}

{% block form%}
<style>
    .errorlist {
        color: red;
    }
</style> {% endcomment %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>LVD Suppliers</title>
    <!-- fontawesome cdn -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
      integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"/>

    <!-- bootstrap css -->
    <link rel="stylesheet" href="/static/home/bootstrap-5.0.2-dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"/>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>
    <link rel="stylesheet" href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>

    <!-- custom css -->
    <link rel="stylesheet" href="/static/home/css/main.css" />
    <link rel="stylesheet" href="/static/home/css/style.css" />
  </head>
  <body>
    <!-- navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-white py-4 fixed-top">
      <div class="container">
        <a class="navbar-brand d-flex justify-content-between align-items-center order-lg-0" href="{%  url 'home:home' %}">
          <img src="/static/home/images/lvd.png" alt="site icon" />
          <span class="text-uppercase fw-lighter ms-2">Suppliers</span>
        </a>
          <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target="#navMenu">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse order-lg-1" id="navMenu">
            <ul class="navbar-nav mx-auto text-center">
              <li class="nav-item px-2 py-2">
                <a class="nav-link text-uppercase text-dark" href="{% url 'home:home' %}">home</a>
              </li>
              <li class="nav-item px-2 py-2">
                <a class="nav-link text-uppercase text-dark" href="{% url 'home:allproduct' %}">product</a>
              </li>
              <li class="nav-item px-2 py-2">
                <a class="nav-link text-uppercase text-dark" href="{% url 'home:collections' %}">collections</a>
              </li>
              <li class="nav-item px-2 py-2">
                <a class="nav-link text-uppercase text-dark" href="#about">about us</a>
              </li>
              <li class="nav-item px-2 py-2 border-0">
                <a class="nav-link text-uppercase text-dark" href="#contact">Contact</a>
              </li>
            </ul>

        {% if request.user.customer %}
          <div class="myprofile">
            <span>Welcome,{{customer.user.username}}</span>
            <div class="info-profile">
              <a href="{% url 'home:customerprofile' %}">My Profile</a>
              <a href="{% url 'home:myorder' %}">My order</a>
              <a href="/accounts/customerlogout">Logout</a>
            </div>
          </div>
          <div class="icon">
            <a href="{% url 'home:mycart' %}"><i class="fa fa-shopping-cart"></i></a>
          </div>
          {%else%}
          <div class="dropdown">
            <button><i class="fas fa-user"></i></button>
            <div class="dropdown-options">
              <a href="/accounts/register">Sign Up</a>
              <a href="/accounts/login">Sign In</a>
              <a href="/accounts/adminloginform">Admin Login</a>
            </div>
            {% endif %}
            
          </div>
          
        </div>
        
      </div>
      
    </nav>

    <!-- end of navbar -->


<div class="container-form">
    <input type="checkbox" id="check">
    <div class="login form">
      <header>Admin Login Form</header>
      <form action="" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        {% comment %} <input type="text" id="username" name="username" placeholder="username">
        <input type="password" id="password" name="password" placeholder="password"> {% endcomment %}
       <button class="button">Login</button>
       {% if error %}

       <li style="color:red;">{{error}}</li>
 
       {% endif %}
    </form>
    
     
    </div>
 
  </div>

{% comment %} 
{% endblock %} {% endcomment %}

<!--Js-->
<script src="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>
<!-- jquery -->
<script src="/static/home/js/jquery-3.6.0.js"></script>
<!-- isotope js -->
<script src="https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.js"></script>
<!-- bootstrap js -->
 <!-- CSS -->
 <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css"/>
 <!-- Default theme -->
 <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/themes/default.min.css"/>

<script src="/static/home/bootstrap-5.0.2-dist//static/home/js/bootstrap.min.js"></script>
<!-- custom js -->
<script src="/static/home/js/script.js"></script>
<!-- filter js-->
<script src="/static/home/js/filter.js"></script>

<script>
  {% for flashmsg in messages%}
    alertify.set('notifier','position', 'top-right');
    alertify.success('{{flashmsg}}');
  {% endfor %}
</script>

</body>
</html>