dashboard/urls.py
from django.urls import path, include
from.import views
from dashboard.views import DashboardOrderDeleteView, DashboardOrderDetailView, DashboardOrderListView, DashboardOrderStatuChangeView

app_name= 'dashboard'

urlpatterns =[
    # Admin Side pages
    path('',views.DashboardHomeView.as_view(),name = 'home'),


    

    # path("admin-home/", AdminHomeView.as_view(), name="adminhome"),
    path("admin-order/<int:pk>/", DashboardOrderDetailView.as_view(),
         name="adminorderdetail"),

    path("admin-all-orders/", DashboardOrderListView.as_view(), name="adminorderlist"),

    path("admin-order-<int:pk>-change/",
         DashboardOrderStatuChangeView.as_view(), name="adminorderstatuschange"),
         
     path("admin-order/<int:pk>/delete", DashboardOrderDeleteView.as_view(), name="adminorderdelete"),

    
    #Category
    path('categories',views.CategoryListView.as_view(),name = 'categories-list'),
    path('categories/create',views.CategoryCreateView.as_view(),name = 'categories-create'),
    path('categories/<int:pk>/update',views.CategoryUpdateView.as_view(), name = 'categories-update'),
    path('categories/<int:pk>/delete/',views.CategoryDeleteView.as_view(), name = 'categories-delete'), 
    path('categories/<int:pk>/detail/',views.CategoryDetailView.as_view(), name = 'categories-detail'),

    #Brand
    path('brands',views.BrandListView.as_view(),name = 'brands-list'),
    path('brands/create',views.BrandCreateView.as_view(),name = 'brands-create'),
    path('brands/<int:pk>/update',views.BrandUpdateView.as_view(), name = 'brands-update'),
    path('brands/<int:pk>/delete/',views.BrandDeleteView.as_view(), name = 'brands-delete'), 
    path('brands/<int:pk>/detail/',views.BrandDetailView.as_view(), name = 'brands-detail'),

    #Product
    path('products',views.ProductListView.as_view(),name = 'products-list'),
    path('products/create',views.ProductCreateView.as_view(),name = 'products-create'),
    path('products/<int:pk>/update',views.ProductUpdateView.as_view(), name = 'products-update'),
    path('products/<int:pk>/delete/',views.ProductDeleteView.as_view(), name = 'products-delete'), 
    path('products/<int:pk>/detail/',views.ProductDetailView.as_view(), name = 'products-detail'),

    #Customer 
    path('customers',views.CustomerListView.as_view(), name = 'customers-list'),
    path('customers/create',views.CustomerCreateView.as_view(),name = 'customers-create'),
    path('customers/<int:pk>/update',views.CustomerUpdateView.as_view(), name = 'customers-update'),
    path('customers/<int:pk>/delete/',views.CustomerDeleteView.as_view(), name = 'customers-delete'), 
    path('customers/<int:pk>/detail/',views.CustomerDetailView.as_view(), name = 'customers-detail'),
    
    #Order
    path('orders',views.OrderListView.as_view(), name = 'orders-list'),
    path('orders/create',views.OrderCreateView.as_view(),name = 'orders-create'),
    path('orders/<int:pk>/update',views.OrderUpdateView.as_view(), name = 'orders-update'),
    path('orders/<int:pk>/delete/',views.OrderDeleteView.as_view(), name = 'orders-delete'), 
    path('orders/<int:pk>/detail/',views.OrderDetailView.as_view(), name = 'orders-detail'),

    path('admin-order-<int:pk>-ordered_by/order_report/', views.customer_order_report, name='customer-order-report'),

    path('analytics/', views.DashboardAnalyticsView.as_view(), name='analytics'),


#     #Cart
#     path('carts',views.CartProductListView.as_view(), name = 'carts-list'),
#     path('carts/create',views.CartProductCreateView.as_view(),name = 'carts-create'),
#     path('carts/<int:pk>/update',views.CartProductUpdateView.as_view(), name = 'carts-update'),
#     path('carts/<int:pk>/delete/',views.CartProductDeleteView.as_view(), name = 'carts-delete'), 
#     path('carts/<int:pk>/detail/',views.CartProductDetailView.as_view(), name = 'carts-detail'),

    # #Sales
    # path('sales/history/', views.sales_history, name='sales_history'),

]

home/urls.py
from django.contrib import admin
from django.urls import path,include
from home import views
from .views import *
from django.contrib.auth.views import LoginView,LogoutView

app_name = 'home'

urlpatterns =[
    path('/', views.index, name="base"),

    path('', views.IndexView.as_view(), name="home"),

    path('aboutus/', views.aboutus, name="aboutus"),

    path('contactus/', views.contactus, name="contactus"),

    path('allproduct', AllProductView.as_view(), name="allproduct"),

    # path('category/<str:pk>', views.CategoryView.as_view(), name='category'),

    path('create', views.ProductCreateView.as_view(), name='products-create'),

    path('product/<str:pk>',views.productDetails, name='productDetails'),

    path('create', views.CustomerCreateView.as_view(), name='customers-create'),

    path('create',views.OrderCreateView.as_view(), name='orders-create'),

    # path('register/', CustomerRegistrationView.as_view(),name="customerregistration"),

    # path("logout/",CustomerLogoutView.as_view(),name="customerlogout"),

    # path("customerlogin/",CustomerLoginView.as_view(),name="customerlogin"),

    path("profile/",CustomerProfileView.as_view(),name="customerprofile"),
    path("profile/order-<int:pk>/", CustomerOrderDetailView.as_view(),
         name="customerorderdetail"),



    path("myorder/",MyOrderDetailView.as_view(),name="myorder"),

    #cart
    # path("add-to-cart-<int:product_id>/",views.cart_add, name="addtocart"),
    path("add-to-cart-<int:pro_id>/", AddToCartView.as_view(), name="add-to-cart"),
    path("my-cart/", MyCartView.as_view(), name="mycart"),
    path("manage-cart/<int:cp_id>/", ManageCartView.as_view(), name="managecart"),
    path("empty-cart/", EmptyCartView.as_view(), name="emptycart"),

    path("checkout/", CheckoutView.as_view(), name="checkout"),

    

#    path('accounts/', include('accounts.urls', namespace='accounts')),


    #category--collection
    path('collections',views.collections,name="collections"),
    path('collections/<str:slug>',views.collectionsviews, name='collectionsview'),


    #payments   
    path("khalti-request/", KhaltiRequestView.as_view(), name="khaltirequest"),
    path("khalti-verify/", KhaltiVerifyView.as_view(), name="khaltiverify"),
    path("esewa-request/", EsewaRequestView.as_view(), name="esewarequest"),
    path("esewa-verify/", EsewaVerifyView.as_view(), name="esewaverify"),
   

]

lvdsuppliers/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('home/',include('home.urls')),
    path('accounts/',include('accounts.urls')),
    
]
urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dashboard/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import RegexValidator

# Create your models here.

class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=50)

    def __str__(self):
        return self.user.username


#category models
class Category(models.Model):
    title = models.CharField(max_length=255,unique=True)
    slug = models.SlugField()
    image = models.ImageField(upload_to= 'categories/',null=True)
    status = models.BooleanField(default=False, help_text="0_default, 1=Hidden")

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"
        ordering = ('id',)

    def __str__(self):
        return self.title 
    

#Brand Models
class Brand(models.Model):
    brand_code = models.CharField(max_length=200,null=True)
    name = models.CharField(max_length=200)
    slug =models.SlugField()

    class Meta:
        verbose_name ="Brand"
        verbose_name_plural = "brands"
        ordering= ('id',)

    def __str__(self):
        return self.name


class SizeVariant(models.Model):
    size_name = models.CharField(max_length=255)

    def  __str__(self) -> str:
        return self.size_name


#Product models
class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products' ,null=True)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE,related_name='products',blank=True,null=True)
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to = 'products/')
    # size_variant = models.ManyToManyField(SizeVariant, blank=True)
    price = models.PositiveIntegerField()
    slug = models.SlugField()
    description = models.CharField(max_length=300)
    is_latest = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'products'
        ordering = ('id',)
    
    def __str__(self):
        return self.name
    
    
    
class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products/")

    def __str__(self):
        return self.product.title
    
# class ProductSize(models.Model):
#     Size = models.ForeignKey(Size, on_delete=models.CASCADE)
#     product = models.ForeignKey(Product, on_delete=models.CASCADE)
#     count = models.IntegerField(default=1)
    
    
#Customer models
class Customer(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    # username = models.CharField(null=True,max_length=200)
    email_regex = RegexValidator(regex=  r"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$", message="please provide valid email address")
    email = models.EmailField(validators=[email_regex],unique=True)
    fn_regex = RegexValidator(regex=r"^[A-Za-z\s]+$", message="please provide valid Name")
    full_name = models.CharField(validators=[fn_regex],max_length=200, null=True)
    # profile_pic= models.ImageField(upload_to='profile_pic/CustomerProfilePic/',null=True,blank=True)
    address = models.CharField(max_length=40)
    contact_regex = RegexValidator( regex = r"^98\d{8}$",message = "phone number should starts with 98 and have 10 digits")
    contact = models.CharField(max_length=10,validators=[contact_regex],null=True)
    created_date = models.DateTimeField(auto_now_add=True,null=True)
    
    
    def __str__(self):
        return self.full_name
    



#Cart Models
class Cart(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL,null=True,blank=True)
    total = models.PositiveIntegerField(default=0)
    # is_paid = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    # def get_cart_total(self):
    #     cart_products = self.cart_products.all()
    #     price = []
    #     for cart_product in cart_product:
    #         price.append(cart_product.product.price)
    #         if cart_product.sizes:
    #             sizes_price = cart_product.sizes.price
    #             price.append(sizes_price)

    #     return sum(price)
    def __str__(self):
        return "Cart: " + str(self.id)
    

class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete = models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    size_variant = models.ForeignKey(SizeVariant,on_delete=models.SET_NULL, null=True,blank=True)
    subtotal = models.PositiveIntegerField()

    def __str__(self):
        return "Cart: " + str(self.cart.id) + " CartProduct: " + str(self.id)

    # def get_product_price(self):
    #     price = [self.product.price]

    #     if self.sizes:
    #         sizes_price =self.sizes.price
    #         price.append(sizes_price)
        
    #     return sum(price)
        

ORDER_STATUS = (
    ("Order Received", "Order Received"),
    ("Order Processing", "Order Processing"),
    ("On the way", "On the way"),
    ("Order Completed", "Order Completed"),
    ("Order Canceled", "Order Canceled"),
)

METHOD = (
    ("Cash On Delivery", "Cash On Delivery"),
    # ("Khalti", "Khalti"),
    ("Esewa", "Esewa"),
)


class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ob_regex = RegexValidator(regex=r"^[A-Za-z\s]+$", message="please provide valid Name")
    ordered_by = models.CharField(validators=[ob_regex],max_length=200)
    shipping_address = models.CharField(max_length=200)
    mobile_regex = RegexValidator( regex = r"^98\d{8}$",message = "phone number should exactly be in 10 digits and starts with 98")
    mobile = models.CharField(max_length=10, validators=[mobile_regex])
    email_regex = RegexValidator(regex=  r"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$", message="please provide valid email address")
    email = models.EmailField(validators=[email_regex],null=True, blank=True)
    subtotal = models.PositiveIntegerField()
    # discount = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=50, choices=ORDER_STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    payment_method = models.CharField(
        max_length=20, choices=METHOD, default="Cash On Delivery")
    payment_completed = models.BooleanField(
        default=False, null=True, blank=True)

    def __str__(self):
        return "Order: " + str(self.id)
    

# class Sale(models.Model):
#     date = models.DateTimeField()
#     amount = models.DecimalField(max_digits=10,decimal_places=2)

#     def __str__(self):
#         return f"Sale on {self.date} - ${self.amount}"

dashboard/forms.py
from django import forms

from . import models

class CategoryForm(forms.ModelForm):

    class Meta:
        model = models.Category
        exclude = []

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update(
                {
                    'class': 'form-control',
                }
            )

class BrandForm(forms.ModelForm):

    class Meta:
        model = models.Brand
        exclude = []

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update(
                {
                    'class': 'form-control',
                }
            )


class ProductForm(forms.ModelForm):

    class Meta:
        model = models.Product
        exclude = []

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update(
                {
                    'class': 'form-control',
                }
            )

class CustomerForm(forms.ModelForm):

    class Meta:
        model = models.Customer
        exclude = []

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update(
                {
                    'class' : 'form-control',
                }
            )


class OrderForm(forms.ModelForm):

    class Meta:
        model = models.Order
        exclude = []
        
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update(
                {
                    'class' : 'form-control',
                }
            )


class CartForm(forms.ModelForm):

    class Meta:
        model = models.Cart
        exclude = []
        
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update(
                {
                    'class' : 'form-control',
                }
            )

dashboard/templates/dashboard/orders/adminorderdetail.html
{% extends 'dashboard/base.html' %}

{% block main %}

<div class="card" id="invoice-content">
    <div class="card-body">
      <div class="container mb-5 mt-3">
        <div class="row d-flex align-items-baseline">
          <div class="col-xl-9">
            <p style="color: #7e8d9f;font-size: 20px;">ORDER >> <strong>ID: #ORDER_{{ord_obj.id}}</strong></p>
          </div>
          <div class="col-xl-3 float-end">
            <a class="btn btn-light text-capitalize border-0" data-mdb-ripple-color="dark"><i
                class="fas fa-print text-primary"></i> Print</a>
            <a class="btn btn-light text-capitalize" data-mdb-ripple-color="dark"><i
                class="far fa-file-pdf text-danger"></i> Export</a>
          </div>
          <hr>
        </div>
  
        <div class="container" id="invoice-content">
          <div class="col-md-12">
            <div class="text-center">
              <i class="fab fa-mdb fa-4x ms-0" style="color:#5d9fc5 ;"></i>
              <p class="pt-0">MDBootstrap.com</p>
            </div>
  
          </div>
  
  
          <div class="row">
            <div class="col-xl-8">
              <ul class="list-unstyled">
                <li class="text-muted">To: <span style="color:#5d9fc5 ;">{{ord_obj.ordered_by}}</span></li>
                <li class="text-muted">{{ord_obj.shipping_address}}</li>
                <li class="text-muted"><i class="fas fa-phone"></i> {{ord_obj.mobile}}</li>
              </ul>
            </div>
            <div class="col-xl-4">
              <p class="text-muted">Order</p>
              <ul class="list-unstyled">
                <li class="text-muted"><i class="fas fa-circle" style="color:#84B0CA ;"></i> <span
                    class="fw-bold">ID:</span>#ORDER_{{ord_obj.id}}</li>
                <li class="text-muted"><i class="fas fa-circle" style="color:#84B0CA ;"></i> <span
                    class="fw-bold">Creation Date: </span>{{ord_obj.created_at}}</li>
                <li class="text-muted"><i class="fas fa-circle" style="color:#84B0CA ;"></i> <span
                    class="me-1 fw-bold">Status:</span><span class="badge bg-warning text-black fw-bold">
                        {{ord_obj.order_status}}</span></li>
              </ul>
            </div>
          </div>
  
          <div class="row my-2 mx-1 justify-content-center">
            <table class="table table-striped table-borderless">
              <thead style="background-color:#84B0CA ;" class="text-white">
                <tr>
                  <th scope="col">SN</th>
                  <th scope="col">Items</th>
                  <th scope="col">Rate</th>
                  <th scope="col">Quantity</th>
                  <th scope="col">Subtotal</th>
                </tr>
              </thead>
              <tbody>
                {% for cp in ord_obj.cart.cartproduct_set.all %}
                <tr>
                  <th scope="row">{{forloop.counter}}</th>
                  <td><a target="_blank"
                    href="{% url 'home:productDetails' cp.product.id %}">{{cp.product.name}}({{cp.product.id}})</a>
                    </td>
                  <td>{{cp.rate}}</td>
                  <td>{{cp.quantity}}</td>
                  <td>{{cp.subtotal}}</td>
                </tr>
                {% endfor %}
              </tbody>
  
            </table>
          </div>
          <div class="row">
            <div class="col-xl-8">
              <p class="ms-3">Add additional notes and payment information</p>
  
            </div>
            <div class="col-xl-3">
              <p class="text-black float-start"><span class="text-black me-3"> Total Amount</span><span
                  style="font-size: 25px;">{{ord_obj.total}}/-</span></p>
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-xl-10">
              <p>Thank you for your purchase</p>
            </div>
            <form action="{% url 'dashboard:adminorderstatuschange' ord_obj.id %}" method="POST">
                {% csrf_token %}
                <select name="status">
                    {% for i, j in allstatus %}
                    <option value="{{i}}" {% if i == ord_obj.order_status %}selected{% endif %}>{{j}}</option>
                    {% endfor %}
                </select>
                <button class="btn btn-success">Change</button>
                <button class="btn btn-primary" onclick="generateReport()"> <i class="fas fa-file"></i></button>
            </form>
          </div>
  
        </div>
      </div>
    </div>
  </div>

  <script>
    {% comment %} function generatePDF() {
        // Create a new jsPDF instance
        const doc = new jsPDF();
      
        // Define the HTML content to be converted to PDF
        const htmlContent = document.getElementById('invoice-content').innerHTML;
      
        // Add HTML content to the PDF
        doc.fromHTML(htmlContent, 15, 15,{
            width: 170
        });
      
        // Save or download the PDF
        doc.save('dashboard/orders/invoice.pdf');
      }
       {% endcomment %}
       function generateReport() {
       // Create a new jsPDF instance
        const doc = new jsPDF();

        // Define the HTML content to be converted to PDF
        const htmlContent = document.getElementById('invoice-content').innerHTML;

        // Add HTML content to the PDF
        doc.fromHTML(htmlContent, 15, 15, {
            width: 170
        });

        // Save or download the PDF
        doc.save('invoice_bill.pdf');
      }
  </script>

{% endblock%}

dashboard/templates/dashboard/orders/list.html
{% extends 'dashboard/base.html' %}

{% block main %}
                <!-- Page Heading -->
               
                <!-- DataTales Example -->
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">Order</h6>
                        <div class="float-right">
                            <a href="{% url 'dashboard:orders-create' %}" class = "btn btn-primary">
                                <i class="fa fa-plus"></i>&nbsp; Order
                            </a>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th>SN</th>
                                        <th/>Cart</th>
                                        <th>Ordered_by</th>
                                        <th>Shipping Address</th>
                                        <th>Contact</th>
                                        <th>Email</th>
                                        <th>Sub Total</th>
                                        <th>Total</th>
                                        <th>Order Status</th>
                                        <th>Created At</th>
                                        <th>Payment Method</th>
                                        <th>Payment completed</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                
                                <tbody>
                                    {% for object in object_list %}
                                    <tr>
                                        <td>{{ forloop.counter }}</td>
                                        <td>{{ object.cart }}</td>
                                        <td>{{ object.ordered_by }}</td>
                                        <td>{{ object.shipping_address }}</td>
                                        <td>{{ object.mobile }}</td>
                                        <td>{{ object.email }}</td>
                                        <td>{{ object.subtotal }}</td>
                                        <td>{{ object.total }}</td>
                                        <td>{{ object.order_status }}</td>
                                        <td>{{ object.created_at }}</td>
                                        <td>{{ object.payment_method }}</td>
                                        <td>{{ object.payment_completed }}</td>
                                        
                                        <td>
                                            <div class="btn-group" role="group">
                                                <a href="{% url 'dashboard:orders-update' object.pk %}" class="btn btn-info btn-sm">
                                                    <i class="fas fa-pen"></i>
                                                   </a> 
                                               {% if not object.non_deletetable %}
                                               <form action="{% url 'dashboard:orders-delete' object.pk %}" method="post">

                                                
                                                {% csrf_token %}
                                                <button class="btn btn-danger btn-sm delete-link ml-2" data-tooltip="tooltip" title="Delete">
                                                    <e class="far fa-trash-alt"></e>
                                                </button>
                                               </form>
                                               {% endif %}
                                            </div>
                                           </td>
                                       

                                    </tr>
                                    {% endfor %}
                                    
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>



{% endblock main %}