accounts/urls.py
from django.urls import path,include
from . import views 
from .views import *
from django.contrib.auth.views import LoginView, LogoutView





app_name = 'accounts'

urlpatterns = [
   # path('adminclick', views.adminLoginView),
   # path('adminlogin', LoginView.as_view(template_name='account/adminlogin.html'),name='adminlogin'),
   # path('afterlogin', views.afterlogin_view,name='afterlogin'),
   # path('logout', LogoutView.as_view(template_name='ecom/logout.html'),name='logout'),
   # path('logout', views.customerSignUpView(), name = 'logout')


   path("register/",
         CustomerRegistrationView.as_view(), name="customerregistration"),

    path("logout/", CustomerLogoutView.as_view(), name="customerlogout"),
    path("login/", CustomerLoginView.as_view(), name="customerlogin"), 


   # path('login',views.AdminLoginViews.as_view(),name='login'),
   path('adminlogout',views.AdminLogoutViews.as_view(),name='adminlogout'),


   # path("registerform/",views.registerform, name="registerform"),
   # path("loginform/",views.loginform, name="loginform"),
   path("adminloginform/",AdminLoginViews.as_view(), name="adminloginform"),
   # path('logout/', views.logoutuser),



]

dashboard/urls.py
from django.urls import path, include
from.import views
from dashboard.views import DashboardOrderDeleteView, DashboardOrderDetailView, DashboardOrderListView, DashboardOrderStatuChangeView

app_name= 'dashboard'

urlpatterns =[
    # Admin Side pages
    path('',views.DashboardHomeView.as_view(),name = 'home'),


    

    # path("admin-home/", AdminHomeView.as_view(), name="adminhome"),
    path("admin-order/<int:pk>/", DashboardOrderDetailView.as_view(),
         name="adminorderdetail"),

    path("admin-all-orders/", DashboardOrderListView.as_view(), name="adminorderlist"),

    path("admin-order-<int:pk>-change/",
         DashboardOrderStatuChangeView.as_view(), name="adminorderstatuschange"),
         
     path("admin-order/<int:pk>/delete", DashboardOrderDeleteView.as_view(), name="adminorderdelete"),

    
    #Category
    path('categories',views.CategoryListView.as_view(),name = 'categories-list'),
    path('categories/create',views.CategoryCreateView.as_view(),name = 'categories-create'),
    path('categories/<int:pk>/update',views.CategoryUpdateView.as_view(), name = 'categories-update'),
    path('categories/<int:pk>/delete/',views.CategoryDeleteView.as_view(), name = 'categories-delete'), 
    path('categories/<int:pk>/detail/',views.CategoryDetailView.as_view(), name = 'categories-detail'),

    #Brand
    path('brands',views.BrandListView.as_view(),name = 'brands-list'),
    path('brands/create',views.BrandCreateView.as_view(),name = 'brands-create'),
    path('brands/<int:pk>/update',views.BrandUpdateView.as_view(), name = 'brands-update'),
    path('brands/<int:pk>/delete/',views.BrandDeleteView.as_view(), name = 'brands-delete'), 
    path('brands/<int:pk>/detail/',views.BrandDetailView.as_view(), name = 'brands-detail'),

    #Product
    path('products',views.ProductListView.as_view(),name = 'products-list'),
    path('products/create',views.ProductCreateView.as_view(),name = 'products-create'),
    path('products/<int:pk>/update',views.ProductUpdateView.as_view(), name = 'products-update'),
    path('products/<int:pk>/delete/',views.ProductDeleteView.as_view(), name = 'products-delete'), 
    path('products/<int:pk>/detail/',views.ProductDetailView.as_view(), name = 'products-detail'),

    #Customer 
    path('customers',views.CustomerListView.as_view(), name = 'customers-list'),
    path('customers/create',views.CustomerCreateView.as_view(),name = 'customers-create'),
    path('customers/<int:pk>/update',views.CustomerUpdateView.as_view(), name = 'customers-update'),
    path('customers/<int:pk>/delete/',views.CustomerDeleteView.as_view(), name = 'customers-delete'), 
    path('customers/<int:pk>/detail/',views.CustomerDetailView.as_view(), name = 'customers-detail'),
    
    #Order
    path('orders',views.OrderListView.as_view(), name = 'orders-list'),
    path('orders/create',views.OrderCreateView.as_view(),name = 'orders-create'),
    path('orders/<int:pk>/update',views.OrderUpdateView.as_view(), name = 'orders-update'),
    path('orders/<int:pk>/delete/',views.OrderDeleteView.as_view(), name = 'orders-delete'), 
    path('orders/<int:pk>/detail/',views.OrderDetailView.as_view(), name = 'orders-detail'),

    path('admin-order-<int:pk>-ordered_by/order_report/', views.customer_order_report, name='customer-order-report'),

    path('analytics/', views.DashboardAnalyticsView.as_view(), name='analytics'),


#     #Cart
#     path('carts',views.CartProductListView.as_view(), name = 'carts-list'),
#     path('carts/create',views.CartProductCreateView.as_view(),name = 'carts-create'),
#     path('carts/<int:pk>/update',views.CartProductUpdateView.as_view(), name = 'carts-update'),
#     path('carts/<int:pk>/delete/',views.CartProductDeleteView.as_view(), name = 'carts-delete'), 
#     path('carts/<int:pk>/detail/',views.CartProductDetailView.as_view(), name = 'carts-detail'),

    # #Sales
    # path('sales/history/', views.sales_history, name='sales_history'),

]

home/urls.py
from django.contrib import admin
from django.urls import path,include
from home import views
from .views import *
from django.contrib.auth.views import LoginView,LogoutView

app_name = 'home'

urlpatterns =[
    path('/', views.index, name="base"),

    path('', views.IndexView.as_view(), name="home"),

    path('aboutus/', views.aboutus, name="aboutus"),

    path('contactus/', views.contactus, name="contactus"),

    path('allproduct', AllProductView.as_view(), name="allproduct"),

    # path('category/<str:pk>', views.CategoryView.as_view(), name='category'),

    path('create', views.ProductCreateView.as_view(), name='products-create'),

    path('product/<str:pk>',views.productDetails, name='productDetails'),

    path('create', views.CustomerCreateView.as_view(), name='customers-create'),

    path('create',views.OrderCreateView.as_view(), name='orders-create'),

    # path('register/', CustomerRegistrationView.as_view(),name="customerregistration"),

    # path("logout/",CustomerLogoutView.as_view(),name="customerlogout"),

    # path("customerlogin/",CustomerLoginView.as_view(),name="customerlogin"),

    path("profile/",CustomerProfileView.as_view(),name="customerprofile"),
    path("profile/order-<int:pk>/", CustomerOrderDetailView.as_view(),
         name="customerorderdetail"),



    path("myorder/",MyOrderDetailView.as_view(),name="myorder"),

    #cart
    # path("add-to-cart-<int:product_id>/",views.cart_add, name="addtocart"),
    path("add-to-cart-<int:pro_id>/", AddToCartView.as_view(), name="add-to-cart"),
    path("my-cart/", MyCartView.as_view(), name="mycart"),
    path("manage-cart/<int:cp_id>/", ManageCartView.as_view(), name="managecart"),
    path("empty-cart/", EmptyCartView.as_view(), name="emptycart"),

    path("checkout/", CheckoutView.as_view(), name="checkout"),

    

#    path('accounts/', include('accounts.urls', namespace='accounts')),


    #category--collection
    path('collections',views.collections,name="collections"),
    path('collections/<str:slug>',views.collectionsviews, name='collectionsview'),


    #payments   
    path("khalti-request/", KhaltiRequestView.as_view(), name="khaltirequest"),
    path("khalti-verify/", KhaltiVerifyView.as_view(), name="khaltiverify"),
    path("esewa-request/", EsewaRequestView.as_view(), name="esewarequest"),
    path("esewa-verify/", EsewaVerifyView.as_view(), name="esewaverify"),
   

]

lvdsuppliers/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('home/',include('home.urls')),
    path('accounts/',include('accounts.urls')),
    
]
urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dashboard/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import RegexValidator

# Create your models here.

class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=50)

    def __str__(self):
        return self.user.username


#category models
class Category(models.Model):
    title = models.CharField(max_length=255,unique=True)
    slug = models.SlugField()
    image = models.ImageField(upload_to= 'categories/',null=True)
    status = models.BooleanField(default=False, help_text="0_default, 1=Hidden")

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"
        ordering = ('id',)

    def __str__(self):
        return self.title 
    

#Brand Models
class Brand(models.Model):
    brand_code = models.CharField(max_length=200,null=True)
    name = models.CharField(max_length=200)
    slug =models.SlugField()

    class Meta:
        verbose_name ="Brand"
        verbose_name_plural = "brands"
        ordering= ('id',)

    def __str__(self):
        return self.name


class SizeVariant(models.Model):
    size_name = models.CharField(max_length=255)

    def  __str__(self) -> str:
        return self.size_name


#Product models
class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products' ,null=True)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE,related_name='products',blank=True,null=True)
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to = 'products/')
    # size_variant = models.ManyToManyField(SizeVariant, blank=True)
    price = models.PositiveIntegerField()
    slug = models.SlugField()
    description = models.CharField(max_length=300)
    is_latest = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'products'
        ordering = ('id',)
    
    def __str__(self):
        return self.name
    
    
    
class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products/")

    def __str__(self):
        return self.product.title
    
# class ProductSize(models.Model):
#     Size = models.ForeignKey(Size, on_delete=models.CASCADE)
#     product = models.ForeignKey(Product, on_delete=models.CASCADE)
#     count = models.IntegerField(default=1)
    
    
#Customer models
class Customer(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    # username = models.CharField(null=True,max_length=200)
    email_regex = RegexValidator(regex=  r"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$", message="please provide valid email address")
    email = models.EmailField(validators=[email_regex],unique=True)
    fn_regex = RegexValidator(regex=r"^[A-Za-z\s]+$", message="please provide valid Name")
    full_name = models.CharField(validators=[fn_regex],max_length=200, null=True)
    # profile_pic= models.ImageField(upload_to='profile_pic/CustomerProfilePic/',null=True,blank=True)
    address = models.CharField(max_length=40)
    contact_regex = RegexValidator( regex = r"^98\d{8}$",message = "phone number should starts with 98 and have 10 digits")
    contact = models.CharField(max_length=10,validators=[contact_regex],null=True)
    created_date = models.DateTimeField(auto_now_add=True,null=True)
    
    
    def __str__(self):
        return self.full_name
    



#Cart Models
class Cart(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL,null=True,blank=True)
    total = models.PositiveIntegerField(default=0)
    # is_paid = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    # def get_cart_total(self):
    #     cart_products = self.cart_products.all()
    #     price = []
    #     for cart_product in cart_product:
    #         price.append(cart_product.product.price)
    #         if cart_product.sizes:
    #             sizes_price = cart_product.sizes.price
    #             price.append(sizes_price)

    #     return sum(price)
    def __str__(self):
        return "Cart: " + str(self.id)
    

class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete = models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    size_variant = models.ForeignKey(SizeVariant,on_delete=models.SET_NULL, null=True,blank=True)
    subtotal = models.PositiveIntegerField()

    def __str__(self):
        return "Cart: " + str(self.cart.id) + " CartProduct: " + str(self.id)

    # def get_product_price(self):
    #     price = [self.product.price]

    #     if self.sizes:
    #         sizes_price =self.sizes.price
    #         price.append(sizes_price)
        
    #     return sum(price)
        

ORDER_STATUS = (
    ("Order Received", "Order Received"),
    ("Order Processing", "Order Processing"),
    ("On the way", "On the way"),
    ("Order Completed", "Order Completed"),
    ("Order Canceled", "Order Canceled"),
)

METHOD = (
    ("Cash On Delivery", "Cash On Delivery"),
    # ("Khalti", "Khalti"),
    ("Esewa", "Esewa"),
)


class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ob_regex = RegexValidator(regex=r"^[A-Za-z\s]+$", message="please provide valid Name")
    ordered_by = models.CharField(validators=[ob_regex],max_length=200)
    shipping_address = models.CharField(max_length=200)
    mobile_regex = RegexValidator( regex = r"^98\d{8}$",message = "phone number should exactly be in 10 digits and starts with 98")
    mobile = models.CharField(max_length=10, validators=[mobile_regex])
    email_regex = RegexValidator(regex=  r"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$", message="please provide valid email address")
    email = models.EmailField(validators=[email_regex],null=True, blank=True)
    subtotal = models.PositiveIntegerField()
    # discount = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=50, choices=ORDER_STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    payment_method = models.CharField(
        max_length=20, choices=METHOD, default="Cash On Delivery")
    payment_completed = models.BooleanField(
        default=False, null=True, blank=True)

    def __str__(self):
        return "Order: " + str(self.id)
    

# class Sale(models.Model):
#     date = models.DateTimeField()
#     amount = models.DecimalField(max_digits=10,decimal_places=2)

#     def __str__(self):
#         return f"Sale on {self.date} - ${self.amount}"

dashboard/forms.py
from django import forms

from . import models

class CategoryForm(forms.ModelForm):

    class Meta:
        model = models.Category
        exclude = []

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update(
                {
                    'class': 'form-control',
                }
            )

class BrandForm(forms.ModelForm):

    class Meta:
        model = models.Brand
        exclude = []

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update(
                {
                    'class': 'form-control',
                }
            )


class ProductForm(forms.ModelForm):

    class Meta:
        model = models.Product
        exclude = []

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update(
                {
                    'class': 'form-control',
                }
            )

class CustomerForm(forms.ModelForm):

    class Meta:
        model = models.Customer
        exclude = []

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update(
                {
                    'class' : 'form-control',
                }
            )


class OrderForm(forms.ModelForm):

    class Meta:
        model = models.Order
        exclude = []
        
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update(
                {
                    'class' : 'form-control',
                }
            )


class CartForm(forms.ModelForm):

    class Meta:
        model = models.Cart
        exclude = []
        
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update(
                {
                    'class' : 'form-control',
                }
            )

dashboard/templates/dashboard/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>Admin Dashboard</title>

    <!-- Custom fonts for this template-->
    <link
      href="/static/dashboard/vendor/fontawesome-free/css/all.min.css"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
      rel="stylesheet"
    />

    <!-- Custom styles for this template-->
    <link href="/static/dashboard/css/sb-admin-2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/2.0.5/FileSaver.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.4.0/jspdf.umd.min.js"></script>
  </head>

  <body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">
      <!-- Sidebar -->
      <ul
        class="navbar-nav bg-gradient-dark sidebar sidebar-dark accordion"
        id="accordionSidebar"
      >
        <!-- Sidebar - Brand -->

        <a
          class="sidebar-brand d-flex align-items-center justify-content-center"
          href="#"
        >
          <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-smile"></i>
          </div>
          <div class="sidebar-brand-text mx-3">Admin section</div>
        </a>

        <!-- Divider -->
        <hr class="sidebar-divider my-0" />

        <!-- Nav Item - Dashboard -->
        {% comment %}
        <li class="nav-item active" style="list-style: none">
          <a class="nav-link" href="{% url 'dashboard:products-list' %}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span></a
          >
        </li>
        {% endcomment %}

        <!-- Divider -->
        <hr class="sidebar-divider" />

        <!-- Heading -->
        <div class="sidebar-heading">Manage</div>
        <li class="nav-item" style="list-style: none">
          <a
            class="nav-link"
            href="{% url 'dashboard:analytics' %}"
            aria-expanded="true"
            aria-controls="collapseTwo"
          >
            <i class="fas fa-fw fa-list"></i>
            <span>Overview</span>
          </a>
        </li>
        <li class="nav-item" style="list-style: none">
          <a
            class="nav-link"
            href="{% url 'dashboard:categories-list' %}"
            aria-expanded="true"
            aria-controls="collapseTwo"
          >
            <i class="fas fa-fw fa-list"></i>
            <span>Category</span>
          </a>
        </li>
        <li class="nav-item" style="list-style: none">
          <a
            class="nav-link"
            href="{% url 'dashboard:brands-list' %}"
            aria-expanded="true"
            aria-controls="collapseTwo"
          >
            <i class="fas fa-fw fa-list"></i>
            <span>Brand</span>
          </a>
        </li>
        <li class="nav-item" style="list-style: none">
          <a
            class="nav-link"
            href="{% url 'dashboard:customers-list' %}"
            aria-expanded="true"
            aria-controls="collapseTwo"
          >
            <i class="fas fa-fw fa-list"></i>
            <span>Customer</span>
          </a>
        </li>
        <li class="nav-item" style="list-style: none">
          <a
            class="nav-link"
            href="{% url 'dashboard:products-list' %}"
            aria-expanded="true"
            aria-controls="collapseTwo"
          >
            <i class="fas fa-fw fa-list"></i>
            <span>Product</span>
          </a>
        </li>
        <li class="nav-item" style="list-style: none">
          <a
            class="nav-link"
            href="{% url 'dashboard:adminorderlist' %}"
            aria-expanded="true"
            aria-controls="collapseTwo"
          >
            <i class="fas fa-fw fa-list"></i>
            <span>Order</span>
          </a>
        </li>
        {% comment %}
        <li class="nav-item" style="list-style: none">
          <a
            class="nav-link"
            href="{% url 'dashboard:carts-list' %}"
            aria-expanded="true"
            aria-controls="collapseTwo"
          >
            <i class="fas fa-fw fa-list"></i>
            <span>Cart</span>
          </a>
        </li>
        {% endcomment %} {% comment %}
        <li class="nav-item" style="list-style: none">
          <a
            class="nav-link"
            href="{% url 'dashboard:sales_history' %}"
            aria-expanded="true"
            aria-controls="collapseTwo"
          >
            <i class="fas fa-fw fa-list"></i>
            <span>Sales</span>
          </a>
        </li>
        {% endcomment %}

        <li class="nav-item" style="list-style: none">
          <a
            class="nav-link"
            href="{% url 'accounts:adminlogout'}"
            data-toggle="modal"
            data-target="#logoutModal"
            aria-expanded="true"
            aria-controls="collapseTwo"
          >
            <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
            <span>Logout</span>
          </a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider" />
      </ul>
      <!-- End of Sidebar -->

      <!-- Logout Modal-->
      <div
        class="modal fade"
        id="logoutModal"
        tabindex="-1"
        role="dialog"
        aria-labelledby="exampleModalLabel"
        aria-hidden="true"
      >
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">
                Ready to Leave?
              </h5>
              <button
                class="close"
                type="button"
                data-dismiss="modal"
                aria-label="Close"
              >
                <span aria-hidden="true">×</span>
              </button>
            </div>
            <div class="modal-body">
              Select "Logout" below if you are ready to end your current
              session.
            </div>
            <div class="modal-footer">
              <button
                class="btn btn-secondary"
                type="button"
                data-dismiss="modal"
              >
                Cancel
              </button>
              <a class="btn btn-primary" href="{% url 'accounts:adminlogout' %}"
                >Logout</a
              >
            </div>
          </div>
        </div>
      </div>
      <!-- Content Wrapper -->
      <div id="content-wrapper" class="d-flex flex-column">
        <!-- Main Content -->
        <div id="content">
          <!-- Topbar -->
          <nav
            class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow"
          >
            <!-- Sidebar Toggle (Topbar) -->
            <button
              id="sidebarToggleTop"
              class="btn btn-link d-md-none rounded-circle mr-3"
            >
              <i class="fa fa-bars"></i>
            </button>
          </nav>
          <!-- End of Topbar -->

          <!-- Begin Page Content -->
          <div class="container-fluid">
            {% block main %} {% endblock main %}
          </div>
          <!-- /.container-fluid -->
        </div>
        <!-- End of Main Content -->
        {% comment %}
        <!-- Footer -->
        <footer class="sticky-footer bg-white">
          <div class="container my-auto">
            <div class="copyright text-center my-auto">
              <span>Copyright &copy; Your Website 2022</span>
            </div>
          </div>
        </footer>
        <!-- End of Footer -->
        {% endcomment %}
      </div>
      <!-- End of Content Wrapper -->
    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div
      class="modal fade"
      id="logoutModal"
      tabindex="-1"
      role="dialog"
      aria-labelledby="exampleModalLabel"
      aria-hidden="true"
    >
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
            <button
              class="close"
              type="button"
              data-dismiss="modal"
              aria-label="Close"
            >
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">
            Select "Logout" below if you are ready to end your current session.
          </div>
          <div class="modal-footer">
            <button
              class="btn btn-secondary"
              type="button"
              data-dismiss="modal"
            >
              Cancel
            </button>
            <a class="btn btn-primary" href="/dashboard/accounts/adminlogout"
              >Logout</a
            >
          </div>
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>
    <!-- CSS -->
    <link
      rel="stylesheet"
      href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css"
    />
    <!-- Default theme -->
    <link
      rel="stylesheet"
      href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/themes/default.min.css"
    />

    <script src="/static/dashboard/vendor/jquery/jquery.min.js"></script>
    <script src="/static/dashboard/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="/static/dashboard/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="/static/dashboard/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="/static/dashboard/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="/static/dashboard/vendor/datatables/dataTables.bootstrap4.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="/static/dashboard/js/demo/datatables-demo.js"></script>
    <!-- //delete link script with modal popup -->
    <script>
      $("body").on("click", ".delete-link", function (e) {
        if (!confirm("are you sure you want to delete ? ")) e.preventDefault();
      });
    </script>

    {% block script %} {% endblock script %}
  </body>
</html>

dashboard/templates/dashboard/index.html
{% extends 'dashboard/base.html' %}

{% block main %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3>Pending Orders</h3>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Order ID </th>
                        <th>Customer</th>
                        <th>Ordered On</th>
                        <th>Amount</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order in pendingorders %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td><a href="{% url 'dashboard:adminorderdetail' order.id %}">#ORDER_{{order.id}}</a></td>
                        <td>{{order.ordered_by}}</td>
                        <td>{{order.created_at}}</td>
                        <td>{{order.total}}</td>

                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>


{% endblock main %}

{% block script %}

            

{% endblock script %}